// Icon registry — maps each kebab-case icon name used across the site to its
// lucide-react component (1:1, per CLAUDE.md). The reference sourced icons from
// the full Lucide CDN global; using named imports here lets the bundler
// tree-shake to only the icons actually used, instead of shipping all ~1500.
//
// This covers every icon name referenced anywhere in /design-reference. If a
// later page introduces a new icon, add it here — an unregistered name renders
// the neutral placeholder square (the reference's missing-icon fallback).
import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  Banknote,
  Briefcase,
  Bus,
  CalendarCheck,
  CalendarDays,
  Camera,
  Car,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ClipboardCheck,
  Clock,
  Coffee,
  Cpu,
  Download,
  Drama,
  Droplets,
  ExternalLink,
  Eye,
  FileBadge,
  FileText,
  Flag,
  Flame,
  FolderOpen,
  GraduationCap,
  Hammer,
  Hand,
  HandHeart,
  HeartPulse,
  Info,
  Instagram,
  Landmark,
  LayoutGrid,
  Map,
  MapPin,
  Megaphone,
  Menu,
  MessageCircle,
  MessageSquare,
  Mic,
  Navigation,
  Network,
  NotebookPen,
  Palette,
  Presentation,
  Quote,
  Radio,
  Scale,
  ShieldCheck,
  Shirt,
  SquareParking,
  Sunrise,
  Target,
  Ticket,
  Trophy,
  Play,
  UserRound,
  Users,
  UsersRound,
  Utensils,
  Video,
  Vote,
  X,
} from 'lucide-react';

export const ICONS = {
  'alert-circle': AlertCircle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  award: Award,
  banknote: Banknote,
  briefcase: Briefcase,
  bus: Bus,
  'calendar-check': CalendarCheck,
  'calendar-days': CalendarDays,
  camera: Camera,
  car: Car,
  check: Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'clipboard-check': ClipboardCheck,
  clock: Clock,
  coffee: Coffee,
  cpu: Cpu,
  download: Download,
  drama: Drama,
  droplets: Droplets,
  'external-link': ExternalLink,
  eye: Eye,
  'file-badge': FileBadge,
  'file-text': FileText,
  flag: Flag,
  flame: Flame,
  'folder-open': FolderOpen,
  'graduation-cap': GraduationCap,
  hammer: Hammer,
  hand: Hand,
  'hand-heart': HandHeart,
  'heart-pulse': HeartPulse,
  info: Info,
  instagram: Instagram,
  landmark: Landmark,
  'layout-grid': LayoutGrid,
  map: Map,
  'map-pin': MapPin,
  megaphone: Megaphone,
  menu: Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  mic: Mic,
  navigation: Navigation,
  network: Network,
  'notebook-pen': NotebookPen,
  palette: Palette,
  play: Play,
  presentation: Presentation,
  quote: Quote,
  radio: Radio,
  scale: Scale,
  'shield-check': ShieldCheck,
  shirt: Shirt,
  'square-parking': SquareParking,
  sunrise: Sunrise,
  target: Target,
  ticket: Ticket,
  trophy: Trophy,
  'user-round': UserRound,
  users: Users,
  'users-round': UsersRound,
  utensils: Utensils,
  video: Video,
  vote: Vote,
  x: X,
};
