// Icon registry — maps each kebab-case icon name used across the site to its
// lucide-react component (1:1, per CLAUDE.md). The reference sourced icons from
// the full Lucide CDN global; using named imports here lets the bundler
// tree-shake to only the icons actually used, instead of shipping all ~1500.
//
// This covers every icon name referenced anywhere in /design-reference. If a
// later page introduces a new icon, add it here — an unregistered name renders
// the neutral placeholder square (the reference's missing-icon fallback).
import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Bus,
  CalendarCheck,
  CalendarDays,
  Camera,
  Car,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  ClipboardCheck,
  Clock,
  Coffee,
  Droplets,
  ExternalLink,
  Eye,
  FileBadge,
  FileText,
  Flag,
  Flame,
  GraduationCap,
  Hammer,
  HeartPulse,
  Info,
  Landmark,
  LayoutGrid,
  MapPin,
  Megaphone,
  Mic,
  Navigation,
  Network,
  NotebookPen,
  Presentation,
  Scale,
  ShieldCheck,
  SquareParking,
  Target,
  Ticket,
  Trophy,
  Play,
  Users,
  UsersRound,
  Utensils,
  Vote,
  X,
} from 'lucide-react';

export const ICONS = {
  'alert-circle': AlertCircle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  bus: Bus,
  'calendar-check': CalendarCheck,
  'calendar-days': CalendarDays,
  camera: Camera,
  car: Car,
  check: Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'clipboard-check': ClipboardCheck,
  clock: Clock,
  coffee: Coffee,
  droplets: Droplets,
  'external-link': ExternalLink,
  eye: Eye,
  'file-badge': FileBadge,
  'file-text': FileText,
  flag: Flag,
  flame: Flame,
  'graduation-cap': GraduationCap,
  hammer: Hammer,
  'heart-pulse': HeartPulse,
  info: Info,
  landmark: Landmark,
  'layout-grid': LayoutGrid,
  'map-pin': MapPin,
  megaphone: Megaphone,
  mic: Mic,
  navigation: Navigation,
  network: Network,
  'notebook-pen': NotebookPen,
  play: Play,
  presentation: Presentation,
  scale: Scale,
  'shield-check': ShieldCheck,
  'square-parking': SquareParking,
  target: Target,
  ticket: Ticket,
  trophy: Trophy,
  users: Users,
  'users-round': UsersRound,
  utensils: Utensils,
  vote: Vote,
  x: X,
};
